DROP TABLE IF EXISTS Tbl_report_querypdpj
CREATE TABLE Tbl_report_querypdpj (
    LedgerNo bigint identity,
    JobNo nvarchar(15),
    JobNm nvarchar(100),
    NoPD nvarchar(50),
    TglPD date,
    NoRef nvarchar(50),
    Alokasi nvarchar(50),
    TipeForm nvarchar(50),
    AtasNama nvarchar(100),
    Deskripsi nvarchar(255),
    NoKO nvarchar(15),
    TotalKO money,
    NoTagihan nvarchar(100),
    NoRek nvarchar(30),
    Nama nvarchar(100),
    TotalPD money,
    TglBayar date,
    JenisTrf nvarchar(50),
    BLEAmount money,
    RekId ntext,
    NoPJ nvarchar(50),
    TglPJ date,
    TotalPJ money,
    Saldo money,
    Company nvarchar(100),  
);